services:
  accountdb:
    image: postgres

  fiserv.api:
    image: ${DOCKER_REGISTRY-}fiservapi
    build:
      context: .
      dockerfile: ExternalServices/MockFiservDnaCoreApi/Dockerfile

  account.api:
    image: ${DOCKER_REGISTRY-}accountapi
    build:
      context: .
      dockerfile: Services/AccountService/AccountService.Api/Dockerfile

volumes:
  postgres_account:
